# version: "1"

# fg_color: "default" | name | hex | integer
# bg_color: "default" | name | hex | integer
# modifier: "none" | "bold" | "dim" | "italic" | "underlined" | "slow_blink" | "rapid_blink" | "reversed" | "hidden" | "crossed_out"

theme:
  base:
    bg_color: "#000000"
  tab:
    divider:
      char: "|"
    base:
      fg_color: "#c0c0c0"
      modifier: reversed
    active:
      fg_color: blue
      modifier: reversed
    mouse_over:
      fg_color: green
      modifier: reversed
  header:
    cluster:
      fg_color: magenta
    namespaces:
      fg_color: yellow
  component:
    base:
      fg_color: blue
    title:
      active:
        fg_color: green
      inactive:
        fg_color: blue
    border:
      type: "plain"
      active:
        fg_color: green
      inactive:
        fg_color: blue
      mouse_over:
        fg_color: red
    text:
      search:
        ## 検索フォーム
        form:
          # base:
          #   fg_color: yellow
          prefix:
            fg_color: yellow
          query:
            fg_color: yellow
          suffix:
            fg_color: yellow

        ## 検索にマッチした文字列のハイライト
        highlight:

          ## 検索にマッチした文字列の中でフォーカスしている文字列のハイライト
          focus:
            fg_color: yellow
            modifier: reversed

          ## 検索にマッチした文字列のハイライト
          matches:
            modifier: reversed

      ## マウスで範囲選択したときのハイライト
      selection:
        fg_color: green
        modifier: reversed
