[package]
name = "kubetui"
version = "0.3.3"
authors = ["kosay <ekr59uv25@gmail.com>"]
edition = "2018"

[workspace]
members = [ "tui-wrapper", "event", "ansi", "clipboard-wrapper" ]

[features]
logging = [ "log", "log4rs", "event/logging", "tui-wrapper/logging" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["rt"] }
crossbeam = "0.8"
clap = { version = "2", features = ["wrap_help"] }
clipboard-wrapper = { path = "./clipboard-wrapper" }
tui-wrapper = { path = "./tui-wrapper" }

log4rs = { version = "1", optional = true }
log = { version = "0.4", optional = true }

event = { path = "./event" }
ansi = { path = "./ansi" }


