[package]
name = "kubetui"
version = "0.1.0"
authors = ["kohashimoto <kohashimoto@bbtower.co.jp>"]
edition = "2018"

[workspace]
members = [ "tui-wrapper", "event", "ansi", "clipboard-wrapper" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["rt"] }
crossbeam = "0.8"
unicode-width = "0.1"

clipboard-wrapper = { path = "./clipboard-wrapper" }
tui-wrapper = { path = "./tui-wrapper" }
event = { path = "./event" }
ansi = { path = "./ansi" }


