[package]
name = "kubetui"
version = "0.1.0"
authors = ["kohashimoto <kohashimoto@bbtower.co.jp>"]
edition = "2018"

[workspace]
members = [ "tui-wrapper", "event", "ansi" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.18"
tui = { git = "https://github.com/sarub0b0/tui-rs.git", features = ['crossterm'] }
tokio = { version = "1", features = ["rt"] }
chrono = "0.4"
crossbeam = "0.8"

tui-wrapper = { path = "./tui-wrapper" }
event = { path = "./event" }
ansi = { path = "./ansi" }

[[example]]
name = "select"
path = "example/select.rs"

