[package]
name = "kubetui"
version = "0.3.0"
authors = ["kosay <ekr59uv25@gmail.com>"]
edition = "2018"

[workspace]
members = [ "tui-wrapper", "event", "ansi", "clipboard-wrapper" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["rt"] }
crossbeam = "0.8"
clap = "2"

clipboard-wrapper = { path = "./clipboard-wrapper" }
tui-wrapper = { path = "./tui-wrapper" }
event = { path = "./event" }
ansi = { path = "./ansi" }


