[package]
name = "kubetui"
version = "0.8.2"
authors = ["kosay <ekr59uv25@gmail.com>"]
edition = "2021"
license = "MIT"
description = "kubernetes terminal user interface"
repository = "https://github.com/sarub0b0/kubetui"
keywords = ["kubernetes", "tui", "terminal", "monitor"]

[workspace]
members = [ "tui-wrapper", "event", "ansi", "clipboard-wrapper" ]

[features]
default = []
logging = [ "log", "log4rs", "event/logging", "tui-wrapper/logging" ]
mock = [ "event/mock" ]
mock-failed = [ "event/mock-failed" ]
new-log-stream = [ "event/new-log-stream" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["rt"] }
crossbeam = "0.8"
clap = { version = "3", features = ["wrap_help", "derive"] }
clipboard-wrapper = { path = "./clipboard-wrapper", version = "0.1.0" }
tui-wrapper = { path = "./tui-wrapper", version = "0.1.0" }

log4rs = { version = "1", optional = true }
log = { version = "0.4", optional = true }

event = { path = "./event", version = "0.1.0" }
ansi = { path = "./ansi", version = "0.1.0" }


