name: Test

on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - LICENSE
      - assets/
      - screenshots/
  pull_request:
    branches: [main]
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - LICENSE
      - assets/
      - screenshots/

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Run tests
        run: cargo test --all
