name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Packages
        run: |
          sudo apt install libssl-dev libxcb-shape0-dev libxcb-xfixes0-dev xorg-dev

      - name: Build
        run: cargo build

      - name: Run tests
        run: cargo test --all
